# Use lightweight Python image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .

# Install SciSpaCy and model
RUN pip install --no-cache-dir -r requirements.txt

# Copy frontend code
COPY . .

# Expose port Streamlit uses
EXPOSE 8501

# Run Streamlit app
CMD ["sh", "-c", "streamlit run app.py --server.port ${PORT} --server.address 0.0.0.0"]