# Use a lightweight Python image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy requirements 
COPY requirements.txt .

# Install dependencies 
RUN pip install --no-cache-dir -r requirements.txt 

# 5. Copy the rest of the code 
Copy . . 

# Expose port 
CMD ['uvicorn', 'main:app', '--host', '0.0.0.0', '--port', '8000']

